acls:
    norsys_banner_view:
        type: entity
        class: Norsys\Bundle\BannerBundle\Entity\Banner
        permission: VIEW
    
    norsys_banner_create:
        type: entity
        class: Norsys\Bundle\BannerBundle\Entity\Banner
        permission: CREATE
    
    norsys_banner_update:
        type: entity
        class: Norsys\Bundle\BannerBundle\Entity\Banner
        permission: EDIT
    
    norsys_banner_delete:
        type: entity
        class: Norsys\Bundle\BannerBundle\Entity\Banner
        permission: DELETE